name: Dump Context

on:
  workflow_dispatch:

jobs: 
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump Context
        uses: ./dump-context
