name: Get Latest Release Tag

on:
  workflow_dispatch:

jobs: 
  get-latest-release-tag:
    runs-on: [self-hosted, main]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Latest Release Tag
        id: get-latest-release-tag
        uses: ./get-latest-release-tag
        with:
          auth-token: ${{secrets.BWELL_DEV_PAT}}
          repo: 'mfe-toolkit'
      - run: echo ${{ steps.get-latest-release-tag.outputs.tag }}

